#!/bin/bash

MYDIR=`dirname $0` && [ ! `echo "$0" | grep '^\/'` ] && MYDIR=`pwd`/$MYDIR
DOCKER=`which docker`

PORT=8084
#DOCKIMG=swaggerapi/swagger-ui
DOCKIMG=docker.io/odam/swagger-ui-customized:latest
NAME=swagger-ui

API_URL=http://pmb-bordeaux.fr/api/ODAM/1.0.0/odam-oas3.yaml

usage() {
    echo "usage: sh $0 [-a <API_URL>] [-i <docker image>] [-n <container name>] [-p <port>] help|start|stop|status"
    exit 1
}

# Get Cmd line arguments depending on options
nopt=0
while getopts a:i:p:n: opt
do
       case $opt in
       a) API_URL=$OPTARG
          nopt=$(expr $nopt + 2)
          ;;
       i) DOCKIMG=$OPTARG
          nopt=$(expr $nopt + 2)
          ;;
       p) PORT=$OPTARG
          nopt=$(expr $nopt + 2)
          ;;
       n) NAME=$OPTARG
          nopt=$(expr $nopt + 2)
          ;;
       esac
done

shift $nopt
[ $# -lt 1 ] && echo -n "Error: " && usage

CMD=$1

(cd $MYDIR

case "$CMD" in
   help) usage
          ;;
   restart)
          sh $0 stop
          sh $0 start
          ;;
   start)
          echo -n "Launch $NAME ($DOCKIMG image) (port $PORT) ..."
          $DOCKER run -d -e "API_URL="$API_URL -p $PORT:8080 --name $NAME $DOCKIMG 2>&1 1>/dev/null
          if [ $? -eq 0 ]; then
             echo " OK"
          else
             echo " Failed"
          fi
          ;;
   stop)
          echo -n "Stop $NAME ($DOCKIMG image) (port $PORT) ..."
          $DOCKER rm -f $NAME 2>&1 1>/dev/null
          if [ $? -eq 0 ]; then
             echo " OK"
          else
             echo " Failed"
          fi
          ;;
   status)
          $DOCKER ps -a | grep -E "(NAMES|$NAME)"
          ;;
   *) usage
      exit 2
esac

)
